# Julia Linear Algebra tutorial

In [37]:
using LinearAlgebra
using DataFrames

## Vectors

### Creating a vector

You can create vectors by putting element between square brackets (`[]`), separated by commas `,`.

In [98]:
vec_a = [1 ,2 ,3]

3-element Vector{Int64}:
 1
 2
 3

Vector also support floating point numbers

In [99]:
vec_b = [4.5 ,5 ,6]

3-element Vector{Float64}:
 4.5
 5.0
 6.0

### Basic Vector operations

You can use the `+` operators for vector additions.

In [88]:
vec_a+vec_b

3-element Vector{Float64}:
 5.5
 7.0
 9.0

The `*` operator for scalar vector multiplication.

In [89]:
5*vec_a

3-element Vector{Int64}:
  5
 10
 15

You can use the `'` operator on the vector to get the row version of a vector.

In [92]:
vec_a'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  3

You can use the dot function to get the dot product of two vectors

In [93]:
dot(vec_a,vec_b)

32.5

Or you can use the dot product formula for column vectors ($x^Ty$).

In [101]:
vec_a'*vec_b

32.5

For outer product, you can use the column vectors outer product formula with column vectors ($xy^T$)

In [95]:
vec_a*vec_b'

3×3 Matrix{Float64}:
  4.5   5.0   6.0
  9.0  10.0  12.0
 13.5  15.0  18.0

### Vector norms

You can use the `norm` function from the Linear Algebra package to calculate the norm of vectors. The syntax for the function is `norm(<vec>,n)` For Manhattan norm (one-norm), you will pass in n = 1. For Euclidean norm, you will pass in n = 2.

In [96]:
print(norm(vec_a,1))

6.0

In [97]:
print(norm(vec_b,2))

9.013878188659973

## Matrices

### Creating matrix

You can create matrix by putting elements between square brackets, separated by empty spaces, and using semi-colons to separate rows.

In [23]:
mat_a = [1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

You can also create floating numbers matrices.

In [29]:
mat_b = [1.5 3 4.5;2 4 6;2.5 5 7.5]

3×3 Matrix{Float64}:
 1.5  3.0  4.5
 2.0  4.0  6.0
 2.5  5.0  7.5

You can also convert a `DataFrame` to a `matrix`.

In [45]:
df = DataFrame(A = 1:3, B = 2:2:6, C = ["M", "F", "F"])

3×3 DataFrame
 Row │ A      B      C      
     │ Int64  Int64  String 
─────┼──────────────────────
   1 │     1      2  M
   2 │     2      4  F
   3 │     3      6  F

In [50]:
mat_c = Matrix(df)

3×3 Matrix{Any}:
 1  2  "M"
 2  4  "F"
 3  6  "F"

Note that when converting dataframe to matrix, non-numerical value can also exist in your created matrix. This might cause errors when you try to do operations on your matrices.

### Matrix operations

Addition can also be done with `+` operator.

In [111]:
mat_a+mat_b

3×3 Matrix{Float64}:
 2.5   5.0   7.5
 6.0   9.0  12.0
 9.5  13.0  16.5

Scalar multiplication can also still be done with `*`.

In [112]:
5*mat_a

3×3 Matrix{Int64}:
  5  10  15
 20  25  30
 35  40  45

`*` operator can also be used for matrix multiplication. 

In [113]:
mat_a*mat_b

3×3 Matrix{Float64}:
 13.0  26.0   39.0
 31.0  62.0   93.0
 49.0  98.0  147.0

If you try multiplying two matrices with incompatible dimension, you will receive an error message as followed.

In [116]:
[1;2;3]*mat_a

LoadError: DimensionMismatch: matrix A has dimensions (3,1), matrix B has dimensions (3,3)

You can check the dimensions of your matrices using the `size` function.

In [118]:
size(mat_a)

(3, 3)

Hadamard product can be done with the `.*` operator.

In [114]:
mat_a.*mat_b

3×3 Matrix{Float64}:
  1.5   6.0  13.5
  8.0  20.0  36.0
 17.5  40.0  67.5

`'` is the transpose operator just like with vectors.

In [102]:
mat_a

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [103]:
mat_a'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

Reshaping matrices can be done with `reshape` function.

In [108]:
mat_a_reshaped = reshape(mat_a, (1,9))

1×9 Matrix{Int64}:
 1  4  7  2  5  8  3  6  9

Note that the reshape function create a new matrix with the desired shape instead of actually reshaping the original matrix, so you will want to save the reshaped matrix into some variable to save it.

In [105]:
mat_a

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

If you try to reshape a matrix without enough/ with too much spaces, an error message will pop up.

In [110]:
reshape(mat_a, (1,10))

LoadError: DimensionMismatch: new dimensions (1, 10) must be consistent with array size 9

In [109]:
reshape(mat_a, (1,8))

LoadError: DimensionMismatch: new dimensions (1, 8) must be consistent with array size 9

## Tensors

Tensors is a generalization of vectors and matrices that has more than two dimensions. It is a very powerful tool that helps with a lot of data science models, especially neural networks ones. We won't be covering tensors in this course, but if you want to learn about it and want to use Julia, there is the `tensors` package that supports tensors operations.